# Generated by Django 3.2.3 on 2021-05-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='email',
            field=models.EmailField(default='www@mail.ru', max_length=100, verbose_name='емаил'),
            preserve_default=False,
        ),
    ]
