# Generated by Django 3.2.3 on 2021-05-31 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote_app', '0002_alter_quote_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'permissions': [('list_quotes', 'list quotes')]},
        ),
    ]
